[package]
name = "enigma_machine"
version = "0.1.0"
authors = ["Henry Wallis"]
edition = "2018"

[lib]
name = "enigma_machine"
path = "src/lib/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"