left_rotor:
  number: 2
  setting: 5
  window_letter: 'B'
middle_rotor:
  number: 4
  setting: 5
  window_letter: 'E'
right_rotor:
  number: 6
  setting: 9
  window_letter: 'R'
plugboard: [
  ['U', 'E'],
  ['A', 'Y'],
  ['X', 'V'],
  ['L', 'S'],
]

